name: example

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run_dynamic_steps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # # Add this step to authenticate to GHCR for pulling private images
      # - name: Log in to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Multiple Actions with super-action
        id: super_run
        # Use the pre-built Docker image from GHCR
        # Replace ':main' with ':latest' or a specific version tag if needed
        # uses: docker://ghcr.io/resoft-labs/super-action:main
        uses: resoft-labs/super-action@main # resoft-labs/super-action@v1
        with:
          presets: |
            - node-setup-install
          action_list: |
            - name: Run Build
              run: npm run build
            - name: Run Tests
              run: npm test
          results_output_file: outputs/node_build_test_results.json
          # Explicitly enable results logging (this is the default)
          display_results: "true"

      - name: Upload Node Build & Test Results Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: node-build-test-results
          path: outputs/node_build_test_results.json
          if-no-files-found: warn
