name: presets only

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run_preset_steps:
    runs-on: ubuntu-latest
    steps:
      # No explicit checkout needed if using a preset that includes it
      - name: Checkout code
        uses: actions/checkout@v4

      # Add this step to authenticate to GHCR for pulling private images
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Presets with super-action
        id: super_run
        # Use the pre-built Docker image from GHCR
        # Replace ':main' with ':latest' or a specific version tag if needed
        uses: docker://ghcr.io/resoft-labs/super-action:main
        with:
          # Define presets to run
          presets: |
            - node-setup-install # Includes checkout, node setup, npm install

          # Optionally save results
          # results_output_file: outputs/presets_only_results.json

      # Results are automatically logged by super-action
      # Optionally upload artifact if results_output_file was used
      # - name: Upload Presets Only Results Artifact
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: presets-only-results
      #     path: outputs/presets_only_results.json
      #     if-no-files-found: warn
