name: Publish Docker image

on:
  push:
    branches: ["main"] # Trigger on pushes to the main branch
  # Optionally trigger on release creation
  # release:
  #   types: [published]

permissions:
  contents: read
  packages: write # Needed to push to GHCR

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Use format ghcr.io/owner/repo
          tags: |
            # tag main branch builds with 'main'
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # tag releases with git tag
            type=ref,event=tag
            # tag latest if it's the default branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable build cache using GitHub Actions cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
